# Generated by Django 4.1.5 on 2023-01-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hotelimages',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotelimages',
            name='updated_at',
        ),
    ]
