# Generated by Django 4.1.5 on 2023-01-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_rename_hotelimages_hotelimage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='Adventures',
        ),
        migrations.AlterModelOptions(
            name='adventures',
            options={'verbose_name_plural': 'Adventures'},
        ),
        migrations.RenameField(
            model_name='adventures',
            old_name='amenity_name',
            new_name='adventure_name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='amenities',
            new_name='adventures',
        ),
    ]
