# Generated by Django 4.1.5 on 2023-02-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_hotelbooking_room_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventures',
            name='adventure_description',
            field=models.TextField(default='Description', max_length=250),
        ),
        migrations.AddField(
            model_name='adventures',
            name='adventure_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
        ),
    ]
