# Generated by Django 4.1.5 on 2023-02-17 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_adventures_adventure_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
