# Generated by Django 4.1.5 on 2023-02-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_alter_hotelbooking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='adventures_booked',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_price',
            field=models.IntegerField(default=100),
        ),
    ]
