# Generated by Django 4.1.5 on 2023-03-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0009_hotelbooking_adventures_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='review',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
